name: dbt_airbnb
version: 1.0.0
config-version: 2
profile: dbt_airbnb
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  dbt_airbnb:
    +materialized: view        # default for everything

    src:
      +materialized: ephemeral      # src_listings, src_hosts, src_reviews 

    dim:
      +materialized: table     # dim_listings_cleansed, dim_hosts_cleansed → tables
